"""
Telegram notification module
"""
import os
import json
import html
import time
import requests
from typing import Optional
from datetime import datetime
from ..logger import setup_logger


logger = setup_logger(__name__)


class TelegramNotifier:
    """Send Telegram notifications with AI news digest"""

    def __init__(
        self,
        bot_token: Optional[str] = None,
        chat_id: Optional[str] = None,
        message_thread_id: Optional[str] = None,
        timeout: int = 30
    ):
        self.bot_token = bot_token or os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")
        self.message_thread_id = message_thread_id or os.getenv("TELEGRAM_MESSAGE_THREAD_ID")
        self.timeout = timeout

        if self.bot_token:
            self.api_url = f"https://api.telegram.org/bot{self.bot_token}"
        else:
            self.api_url = None

        if not self.bot_token or not self.chat_id:
            logger.warning("Telegram bot token or chat ID not configured")
        else:
            logger.info(f"TelegramNotifier initialized (chat_id: {self._mask_chat_id(self.chat_id)})")

    def send(
        self,
        content: str,
        title: Optional[str] = None,
        parse_mode: str = "HTML",
        language: str = "en"
    ) -> bool:
        """
        Send Telegram notification with news digest.
        Supports both classic text digest and structured JSON digest.
        """
        if not self.bot_token or not self.chat_id:
            logger.error("Telegram bot token or chat ID is not configured. Skipping Telegram send.")
            return False

        structured_digest = self._parse_structured_digest(content)
        if structured_digest:
            return self._send_structured_digest(structured_digest, title, language)

        try:
            # Classic fallback mode
            if title is None:
                today = datetime.now().strftime("%Y-%m-%d")
                lang_suffix = f" [{language.upper()}]" if language != "en" else ""
                title = f"AI News Digest - {today}{lang_suffix}"

            footer = "\n\n───────────────\n\n<i>Generated by <a href='https://github.com/giftedunicorn/ai-news-bot'>AI News Bot</a></i>"
            content_with_footer = content + footer

            if parse_mode == "HTML":
                message = self._format_html(title, content_with_footer)
            elif parse_mode in ["Markdown", "MarkdownV2"]:
                message = self._format_markdown(title, content_with_footer)
            else:
                message = f"{title}\n\n{content_with_footer}"

            messages = self._split_message(message)

            logger.info(f"Sending {len(messages)} Telegram message(s) to chat {self._mask_chat_id(self.chat_id)}")

            success = True
            for idx, msg in enumerate(messages):
                if not self._send_single_message(msg, parse_mode):
                    success = False
                    logger.error(f"Failed to send message part {idx + 1}/{len(messages)}")
                    break

            if success:
                logger.info("All Telegram messages sent successfully")

            return success

        except Exception as e:
            logger.error(f"Unexpected error sending Telegram message: {str(e)}", exc_info=True)
            return False

    def _parse_structured_digest(self, content: str) -> Optional[dict]:
        """
        Parse structured JSON digest produced by the LLM.
        """
        try:
            clean = content.strip()

            if clean.startswith("```json"):
                clean = clean.removeprefix("```json").strip()
            elif clean.startswith("```"):
                clean = clean.removeprefix("```").strip()

            if clean.endswith("```"):
                clean = clean[:-3].strip()

            # Safety fallback: extract the first JSON object if the model adds accidental text
            if not clean.startswith("{"):
                start = clean.find("{")
                end = clean.rfind("}")
                if start != -1 and end != -1 and end > start:
                    clean = clean[start:end + 1]

            data = json.loads(clean)

            if isinstance(data, dict) and isinstance(data.get("items"), list):
                return data

            return None

        except Exception:
            logger.warning("Content is not structured JSON, falling back to classic Telegram send")
            return None

    def _send_structured_digest(
        self,
        digest: dict,
        title: Optional[str] = None,
        language: str = "en"
    ) -> bool:
        """
        Send structured digest as one Telegram message per news item.
        """
        try:
            today = datetime.now().strftime("%Y-%m-%d")
            lang_suffix = f" [{language.upper()}]" if language != "en" else ""

            if title is None:
                title = f"AI News Digest - {today}{lang_suffix}"

            items = digest.get("items", [])

            if not items:
                logger.error("Structured digest has no items")
                return False

            header = (
                f"<b>🧠 {html.escape(title)}</b>\n\n"
                f"News selezionate: <b>{len(items)}</b>\n"
                f"Ogni notizia è inviata come messaggio separato, così puoi inoltrarla facilmente."
            )

            if not self._send_single_message(header, "HTML"):
                return False

            time.sleep(1.2)

            success = True

            for idx, item in enumerate(items, start=1):
                message = self._format_news_item_message(item, idx)
                source_url = str(item.get("source_url", "")).strip()

                reply_markup = None
                if source_url:
                    reply_markup = {
                        "inline_keyboard": [
                            [
                                {
                                    "text": "🔗 Apri fonte",
                                    "url": source_url
                                }
                            ]
                        ]
                    }

                chunks = self._split_message(message, max_length=3900)

                for chunk_idx, chunk in enumerate(chunks):
                    chunk_markup = reply_markup if chunk_idx == len(chunks) - 1 else None

                    if not self._send_single_message(chunk, "HTML", reply_markup=chunk_markup):
                        success = False
                        logger.error(f"Failed to send structured news item {idx}/{len(items)}")
                        break

                    time.sleep(1.2)

                if not success:
                    break

            if success:
                logger.info("Structured Telegram digest sent successfully")

            return success

        except Exception as e:
            logger.error(f"Unexpected error sending structured Telegram digest: {str(e)}", exc_info=True)
            return False

    def _format_news_item_message(self, item: dict, idx: int) -> str:
        """
        Format a single news item as a Telegram HTML message.
        """
        title = html.escape(str(item.get("title", "Senza titolo")).strip())
        category = html.escape(str(item.get("category", "AI News")).strip())
        summary = html.escape(str(item.get("summary", "")).strip())
        why = html.escape(str(item.get("why_it_matters", "")).strip())
        source_name = html.escape(str(item.get("source_name", "Fonte")).strip())
    
        return (
            f"<b>{idx}. {title}</b>\n\n"
            f"🏷 <i>{category}</i>\n\n"
            f"<b>Riassunto</b>\n"
            f"<i>{summary}</i>\n\n"
            f"<b>Perché è importante</b>\n"
            f"<i>{why}</i>\n\n"
            f"Fonte: {source_name}"
        )

    def _send_single_message(
        self,
        message: str,
        parse_mode: str,
        reply_markup: Optional[dict] = None
    ) -> bool:
        """
        Send a single Telegram message.
        """
        try:
            payload = {
                "chat_id": self.chat_id,
                "text": message,
                "parse_mode": parse_mode,
                "disable_web_page_preview": True
            }

            if reply_markup:
                payload["reply_markup"] = reply_markup

            if self.message_thread_id:
                try:
                    payload["message_thread_id"] = int(self.message_thread_id)
                except ValueError:
                    logger.error("Invalid TELEGRAM_MESSAGE_THREAD_ID: must be an integer")
                    return False

            response = requests.post(
                f"{self.api_url}/sendMessage",
                json=payload,
                timeout=self.timeout
            )
            
            if response.status_code == 429:
                try:
                    retry_after = response.json().get("parameters", {}).get("retry_after", 10)
                except ValueError:
                    retry_after = 10
            
                logger.warning(f"Telegram rate limit hit. Retrying after {retry_after} seconds...")
                time.sleep(int(retry_after) + 1)
            
                response = requests.post(
                    f"{self.api_url}/sendMessage",
                    json=payload,
                    timeout=self.timeout
                )

            response.raise_for_status()
            result = response.json()

            if result.get("ok"):
                return True

            logger.error(f"Telegram API returned error: {result.get('description', 'Unknown error')}")
            return False

        except requests.exceptions.Timeout:
            logger.error(f"Telegram request timed out after {self.timeout} seconds")
            return False
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to send Telegram message: {str(e)}", exc_info=True)
            return False

    def _format_html(self, title: str, content: str) -> str:
        """
        Format message in HTML format for Telegram.
        """
        formatted_content = content

        lines = []
        for line in formatted_content.split('\n'):
            if line.startswith('# '):
                lines.append(f"<b>{line[2:].strip()}</b>")
            elif line.startswith('## '):
                lines.append(f"<b>{line[3:].strip()}</b>")
            elif line.startswith('**') and line.endswith('**'):
                lines.append(f"<b>{line[2:-2]}</b>")
            else:
                lines.append(line)

        formatted_content = '\n'.join(lines)

        return f"<b>{title}</b>\n\n{formatted_content}"

    def _format_markdown(self, title: str, content: str) -> str:
        """
        Format message in Markdown format for Telegram.
        """
        return f"*{title}*\n\n{content}"

    def _split_message(self, message: str, max_length: int = 4096) -> list:
        """
        Split long message into chunks that fit Telegram's character limit.
        """
        if len(message) <= max_length:
            return [message]

        chunks = []
        current_chunk = []
        current_length = 0

        for line in message.split('\n'):
            line_length = len(line) + 1

            if current_length + line_length > max_length:
                if current_chunk:
                    chunks.append('\n'.join(current_chunk))
                current_chunk = [line]
                current_length = line_length
            else:
                current_chunk.append(line)
                current_length += line_length

        if current_chunk:
            chunks.append('\n'.join(current_chunk))

        return chunks

    def _mask_chat_id(self, chat_id: str) -> str:
        """
        Mask chat ID for logging.
        """
        if not chat_id:
            return ""

        chat_id_str = str(chat_id)
        if len(chat_id_str) <= 4:
            return "***"

        return f"{chat_id_str[:2]}***{chat_id_str[-2:]}"
